server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/barrycommins/centralizedconfig-repo
  application:
    name: config-server
management:
  security:
    enabled: false
encrypt:
  key-store:
    alias: config-server-key
    location: "classpath:config-server.jks"
    password: testpass
